#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=7

WIZARD_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
VERIFY="$WIZARD_ROOT/scripts/verify_toolybara_bootstrap.py"
BEFORE_SETTINGS=""
AFTER_SETTINGS=""
TOOLYBARA_PRIVATE_KEY_FILE=""

cleanup() {
  [[ -n "$BEFORE_SETTINGS" ]] && rm -f -- "$BEFORE_SETTINGS"
  [[ -n "$AFTER_SETTINGS" ]] && rm -f -- "$AFTER_SETTINGS"
  unset TOOLYBARA_PRIVATE_KEY
  if [[ -n "$TOOLYBARA_PRIVATE_KEY_FILE" && -e "$TOOLYBARA_PRIVATE_KEY_FILE" ]]; then
    warn "the local Toolybara PEM still exists: $TOOLYBARA_PRIVATE_KEY_FILE"
  fi
}
trap cleanup EXIT

require_command() {
  command -v "$1" >/dev/null 2>&1 || {
    warn "required command is missing: $1"
    exit 1
  }
}

banner "Toolybara GitHub App bootstrap"

stage "Preflight and settings baseline"
say "Run this on Cavallo from the Marketplace repository after reviewing Issue #16."
say "This wizard will create an App, install it, and write one organization variable and one organization secret."
say "It will not change Marketplace repository settings."
require_command gh
require_command python3
require_command openssl
gh auth status --hostname github.com
if ! gh auth status --hostname github.com 2>&1 | grep -q "admin:org"; then
  warn "Writing selected organization Actions credentials requires the admin:org OAuth scope."
  confirm "Authorize the current gh login for admin:org?" || exit 1
  gh auth refresh --hostname github.com --scopes admin:org
fi
python3 "$VERIFY" static
BEFORE_SETTINGS=$(mktemp "${TMPDIR:-/tmp}/toolybara-before.XXXXXX")
python3 "$VERIFY" capture-settings > "$BEFORE_SETTINGS"
say "Captured a read-only Marketplace settings baseline in local ephemeral storage."
pause "Continue to App registration?"

stage "Register Toolybara"
say "Create or verify the private organization-owned GitHub App. Never create a duplicate."
open_url "https://github.com/organizations/toolboxmd/settings/apps"
if confirm "Does an existing Toolybara App appear in this list?"; then
  step "Open Toolybara and verify every value against toolybara/bootstrap-policy.json."
else
  open_url "https://github.com/organizations/toolboxmd/settings/apps/new?name=Toolybara&description=The%20ToolboxMD%20release%20courier.%20Toolybara%20carries%20verified%20ToolboxMD%20releases%20into%20the%20Marketplace%20and%20merges%20them%20when%20every%20check%20is%20green.&url=https%3A%2F%2Fgithub.com%2Ftoolboxmd%2Fmarketplace&public=false&webhook_active=false&contents=write&pull_requests=write"
  step "Review the prefilled name, description, homepage, private visibility, and disabled webhook."
  step "Under Repository permissions, keep only Metadata read-only, Contents read and write, and Pull requests read and write."
  step "Keep all organization and account permissions at No access and subscribe to no events."
  step "Click Create GitHub App."
fi
confirm "Does Toolybara now exactly match the policy file?" || exit 1
step "Capture redacted App-settings evidence for Issue #16 showing private visibility, disabled webhooks, exact repository permissions, no organization or account permissions, and no event subscriptions. Exclude App ID, Client ID, and every credential."
pause "Is the redacted App-settings evidence ready for the later Issue #16 proof handoff?"

stage "Install on Marketplace only"
say "Install one organization copy with selected-repository access."
open_url "https://github.com/organizations/toolboxmd/settings/installations"
if confirm "Is Toolybara already installed for the toolboxmd organization?"; then
  step "Open Configure for Toolybara."
else
  open_url "https://github.com/apps/toolybara/installations/new"
  step "Choose the toolboxmd organization."
fi
step "Select Only select repositories."
step "Select only toolboxmd/marketplace, then save or install."
warn "Do not select AgentsMD and do not select All repositories."
confirm "Is Marketplace the installation's only selected repository?" || exit 1

stage "Store the public client ID"
say "The client ID is public configuration, not a secret."
open_url "https://github.com/organizations/toolboxmd/settings/apps"
step "Open Toolybara, then copy Client ID from About. Do not copy Client secret or App ID."
ask TOOLYBARA_CLIENT_ID "Paste the Toolybara client ID:"
[[ -n "$TOOLYBARA_CLIENT_ID" ]] || { warn "client ID is required"; exit 1; }
confirm "Write TOOLYBARA_CLIENT_ID as an organization variable selected only for agentsmd and marketplace?" || exit 1
gh variable set TOOLYBARA_CLIENT_ID \
  --org toolboxmd \
  --repos agentsmd,marketplace \
  --body "$TOOLYBARA_CLIENT_ID"
say "Stored the public client ID without creating repository-level copies."

stage "Store the private key"
say "Generate one private key and move it directly into the selected organization secret."
open_url "https://github.com/organizations/toolboxmd/settings/apps"
step "Open Toolybara. Under Private keys, click Generate a private key."
step "Keep the downloaded PEM only long enough to store and verify the Actions secret."
ask TOOLYBARA_PRIVATE_KEY_FILE "Paste the absolute path to the downloaded PEM file:"
[[ -f "$TOOLYBARA_PRIVATE_KEY_FILE" ]] || { warn "PEM file not found"; exit 1; }
openssl rsa -in "$TOOLYBARA_PRIVATE_KEY_FILE" -check -noout >/dev/null
TOOLYBARA_PRIVATE_KEY=$(<"$TOOLYBARA_PRIVATE_KEY_FILE")
confirm "Write TOOLYBARA_PRIVATE_KEY as one organization secret selected only for agentsmd and marketplace?" || exit 1
printf '%s' "$TOOLYBARA_PRIVATE_KEY" | gh secret set TOOLYBARA_PRIVATE_KEY \
  --org toolboxmd \
  --repos agentsmd,marketplace
unset TOOLYBARA_PRIVATE_KEY
WRITTEN_SECRET+=("toolboxmd/TOOLYBARA_PRIVATE_KEY")
say "Stored one organization secret. No repository-secret copy was created."

stage "Verify Toolybara identity and scope"
say "Run the fixed workflow from Marketplace main. It mints two independently scoped ephemeral tokens and performs read-only identity and scope checks."
confirm "Dispatch the Toolybara bootstrap verification workflow now?" || exit 1
gh workflow run toolybara-bootstrap-verification.yml \
  --repo toolboxmd/marketplace \
  --ref main
open_url "https://github.com/toolboxmd/marketplace/actions/workflows/toolybara-bootstrap-verification.yml"
step "Open the newest workflow_dispatch run and copy its URL."
ask VERIFICATION_RUN_URL "Paste the verification run URL:"
case "$VERIFICATION_RUN_URL" in
  https://github.com/toolboxmd/marketplace/actions/runs/*) ;;
  *) warn "unexpected Marketplace Actions run URL"; exit 1 ;;
esac
VERIFICATION_RUN_ID=${VERIFICATION_RUN_URL##*/}
gh run watch "$VERIFICATION_RUN_ID" --repo toolboxmd/marketplace --exit-status
say "The run proves the app slug, Marketplace-only token scope, and explicit token permissions without printing credentials."

stage "Prove settings unchanged and clean up"
AFTER_SETTINGS=$(mktemp "${TMPDIR:-/tmp}/toolybara-after.XXXXXX")
python3 "$VERIFY" capture-settings > "$AFTER_SETTINGS"
python3 "$VERIFY" compare-settings "$BEFORE_SETTINGS" "$AFTER_SETTINGS"
python3 "$VERIFY" credential-metadata
say "The before and after snapshots match and credential metadata contains no secret value."
warn "The downloaded PEM is a persistent credential until removed."
confirm "Permanently remove the downloaded PEM file now?" || exit 1
rm -f -- "$TOOLYBARA_PRIVATE_KEY_FILE"
[[ ! -e "$TOOLYBARA_PRIVATE_KEY_FILE" ]] || { warn "PEM removal failed"; exit 1; }
TOOLYBARA_PRIVATE_KEY_FILE=""
say "Removed the local PEM after verification."

finish
